### ISSUE TITLE
Network metrics scripts currently require autotools

### ISSUE THREAD

**Issue by bwarden** [clearcontainers/tests#170]
Need to rework the scripts to be static files with appropriately passed environment variables:
- metrics/network/network-metrics-cpu-consumption.sh.in
- metrics/network/network-metrics-memory-pss-1g.sh.in
- metrics/network/network-metrics-memory-pss.sh.in
- metrics/network/network-metrics-memory-rss-1g.sh.in

Looks like they only need QEMU_PATH.

**Comment by dlespiau** [comment]
Of course, we don't want autotools here, just a makefile rule to generate the file files from the .in files.

**Comment by bwarden** [comment]
I plan to rework the individual scripts to use an environment variable instead, and if necessary, generate a single script that they include, in which the variable is actually defined. If QEMU_PATH is already defined by the test execution process, then I don't even need to generate files.

**Comment by grahamwhaley** [comment]
Personally I prefer pre-setting an ENV var rather than pre-processing the scripts - but it is a bit swings/roundabouts.

We already have a common file for common things:
https://github.com/clearcontainers/tests/blob/master/metrics/lib/common.bash
which may be a convenient place to set the VARS up, and it is already pulled into the one existing metrics test:
https://github.com/clearcontainers/tests/blob/master/metrics/time/docker_workload_time.sh#L27

Just to note, finding the appropriate QEMU is actually quite difficult to get 100% correct. Technically you'd have to, I believe, scour the docker setup to find the correct runtime files, and then scour the runtime config files to locate the actual QEMU binary configured to be used.
That's all a bit tricky, and for now I think we will probably have to do our 'best guess'. @chavafg I believe is the expert here on what the pitfalls are and what is pragmatic to do at present.
