### ISSUE TITLE
integration/docker: change docker stop timeout

### ISSUE THREAD

**Issue by devimc** [clearcontainers/tests#360]
increase the timeout of docker stop

**Comment by sboeuf** [comment]
Notice that docker stop, according to the workload that has been started, takes more or less time because some signals are not handled properly in a way. This needs more investigation but we get the same observations from testing with `runc`.

For instance
```
docker run -td --name test busybox sh
docker stop test
```
takes 10 seconds.

Compared to
```
docker run -td --name test busybox top
docker stop test
```
which takes around 1 second.
