### ISSUE TITLE
Remove test-versions.txt and rely on the clearcontainers/runtime versions.txt

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#759]
Today we have 2 files on different repos which contain information of the dependencies versions we support, but this duplicates information and it is fragile since we can end up updating one, but not the other.

My proposal is to remove `test-versions.txt` from this repository and move all missing info to the `versions.txt` on the runtime repository: https://github.com/clearcontainers/runtime/blob/master/versions.txt 

So instead of sourcing `test-version.txt` in the CI scripts we will need to... 
```
go get github.com/clearcontainers/runtime
source $GOPATH/src/github.com/clearcontainers/runtime/version.txt
```

What do you think ? 
/cc @sboeuf @jodh-intel @grahamwhaley @jcvenegas

**Comment by jodh-intel** [comment]
I agree that we should define all these versions in a single location to avoid the update/sync issue. On  https://github.com/clearcontainers/runtime/issues/608, I mentioned a possible circular dependency issue, but I don't think there really is one given that:

- all repos use `tests`.
- `tests` will always clone the runtime.

Therefore, if, for example, a proxy PR was going to be tested by the CI, the following would happen:

- proxy's CI scripts clone `tests` repo and run setup.
- `tests` setup scripts clone the `runtime` repo.
- `tests` can now access `versions.txt`.

The only problem would be if the tests needed to query `versions.txt` *before* calling `install_runtime.sh` I think. If we ever think that might happen, we should put `versions.txt` somewhere else: a repo that isn't a main component of the system and thus required by the CI. That could either be a new repo entirely or maybe the `packaging` repo?

Related:

- https://github.com/clearcontainers/runtime/issues/608
- https://github.com/clearcontainers/tests/issues/666

**Comment by grahamwhaley** [comment]
Completely agree we should de-duplicate this.
I also agree that if the proposal to place it solely in the runtime repo does not work out, then maybe the packaging repo makes a lot of sense.
+1 that we try the runtime and see if that flies.

**Comment by jodh-intel** [comment]
:airplane: or :boom:

**Comment by chavafg** [comment]
I didn't notice that there was already an issue opened to address this, sorry for opening this one.
@jodh-intel I think we use`versions.txt` before running `install_runtime.sh` and I think we can fix it by running a `go get` the first time we use versions.txt, does this make sense?

And checking the clearcontainers/packaging/versions.txt I see that some of the versions there might be different at some point. For example, currently the clear-containers-image version used in the CI is different than the one that is packaged. This could also happen with the CC kernel. So maybe we should (at least for the moment) keep packaging version intact and try to unify the one in the tests and runtime repos. 
Other option could be to create different variables for these components. E.g. `ci_kernel_version` and `package_kernel_version`.

**Comment by jodh-intel** [comment]
Are you saying that we'd make the CI scripts `go get` the runtime so the scripts can read `versions.txt` 
 such that when `install_runtime.sh` runs:

```
clone_build_and_install "github.com/clearcontainers/runtime"
```

... that is basically a "nop"? If so, I guess that's fine (but read on...)

Regarding the variables, yes I think that your idea would work too. But its starting to get complicated since consumers of `versions.txt` would then need to make decisions as to which variable they should be looking at.

IMHO, we need to have more of a think about the [`manage_ctr_mgr.sh` script idea](https://github.com/clearcontainers/tests/issues/666). This could hide the complexity and provide a simple interface to establishing which kernel/image/docker/etc version a particular scenario should be using.

If we had such a script, it could be invoked at the start of the `tests` CI scripts to:

- DTRT and "find" the appropriate `versions.txt` by `go get`'ing the runtime (or whatever is needed).
- help the test environment find the correct version of assets / middleware / container managers / etc.

What do others think?

**Comment by chavafg** [comment]
@jodh-intel right, when we call `clone_build_and_install` it won't get the repo again as it will already be downloaded, but it will build and install the component.

I agree that `manage_ctr_mgr` should be the one that installs the appropriate components depending on the scenario, but I want to have this versions issue fixed before starting the work on the script, because right now the tool will look for info in both `versions.txt`.

**Comment by jodh-intel** [comment]
Agreed. We need a "quick-ish" solution so putting everything into the runtime's `versions.txt` will have to suffice for now I guess. Atleast then we'll only have 1 file to deal with.
