### ISSUE TITLE
clone tests repo in jenkins_job_build.sh script

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#914]
`jenkins_job_build.sh` should clone `tests` repo to be able to call to `manage_ctr_mgr.sh` 

```
21:23:04 .ci/jenkins_job_build.sh: line 94: /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-fedora-26-PR/go/src/github.com/clearcontainers/tests/cmd/container-manager/manage_ctr_mgr.sh: No such file or directory

```

**Comment by grahamwhaley** [comment]
Late to the party, and I'm sure maybe when I see the PR this might make sense - but - if `jenkins_job_build.sh` lives in the test repo, we must have cloned it already to be able to call the script, so,... why would we hvae to clone it again?
In the Jenkins sciripts (the config scripts on the jenkins servers) afaik we clone the tests repo early on in order to be able to call the `jenkins_job_build.sh`. So, I'm mildly confused :-)

**Comment by chavafg** [comment]
@grahamwhaley sorry for the short description that didn't, help.

The problem here was that in the jenkins job, we clone the repo using `git clone` in the $HOME directory:
https://github.com/clearcontainers/jenkins/blob/master/jobs/clear-containers-runtime-azure-ubuntu-16-04-PR/config.xml#L97-L101

and when calling the `manage_ctr_mgr.sh` script, it was being called using `$GOPATH/src/...` and as that path didn't exist, the CI failed in this step.

**Comment by grahamwhaley** [comment]
Ah, thanks!
For reference, in the metrics CI I do the below, which is why I suspect I don't see the issue:
```
export GOPATH="${WORKSPACE}/go"
...
go get -d -u ${TESTS_REPO_NAME}
```

and then run the jenkins script from that GOPATH/src bsaed repo.
